### ISSUE TITLE
Error installing xslt on GitHub Actions

### ISSUE THREAD

**Issue by jimhester** [ropensci/xslt#9]
Not entirely sure if this is an xslt error, or just something weird on GitHub Actions

```
##[error]Error: package or namespace load failed for ‘xslt’ in dyn.load(file, DLLpath = DLLpath, ...):
ERROR: loading failed
* removing ‘/Users/runner/runners/2.168.0/work/_temp/Library/xslt’
 unable to load shared object '/Users/runner/runners/2.168.0/work/_temp/Library/00LOCK-xslt/00new/xslt/libs/xslt.so':
  dlopen(/Users/runner/runners/2.168.0/work/_temp/Library/00LOCK-xslt/00new/xslt/libs/xslt.so, 6): Symbol not found: _exsltRegisterAll
  Referenced from: /Users/runner/runners/2.168.0/work/_temp/Library/00LOCK-xslt/00new/xslt/libs/xslt.so
  Expected in: flat namespace
 in /Users/runner/runners/2.168.0/work/_temp/Library/00LOCK-xslt/00new/xslt/libs/xslt.so
##[error]Error: loading failed
```

https://github.com/r-lib/xml2/runs/571881855?check_suite_focus=true#step:5:74

The workflow basically was just calling `install.packages("xslt")` and that does work without issue locally, so I am not clear what is different on the GHA runner. Though now that I look at the log it seems like the `PKG_LIBS` are not being added appropriately for some reason 

> Using PKG_LIBS=

https://github.com/r-lib/xml2/runs/571881855?check_suite_focus=true#step:5:55

**Comment by jeroen** [comment]
Ah hmm maybe that could happen if `pkg-config` is missing form the system. I added that workaround for xcode to add the missing sdk path to PKGCONFIG_CFLAGS, but I forgot to condition that on if pkg-config was actually set in the first place.

Either way, installing pkg-config on the server by default may be a good idea?

**Comment by jeroen** [comment]
fixed
